apiVersion: container.gcp.crossplane.io/v1beta1
kind: GKECluster
metadata:
  name: developer-cthorn
spec:
  forProvider:
    location: us-central1-a
    masterAuth:
      username: admin
  writeConnectionSecretToRef:
    name: developer-cthorn
    namespace: crossplane-system
  providerConfigRef:
    name: default
  reclaimPolicy: Delete
  initialNodeCount: 1
